name: xai-eval
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip:
    - -r requirements-frozen.txt
    - tensorflow-cpu
    - alibi
    - dice-ml
