project:
  type: book
  output-dir: _output

book:
  title: "JHerrera_XAI_Tesis_Doctorado"
  author: "J. Herrera"
  date: "2026"
  chapters:
    - index.qmd
    - 01-introduccion.qmd
    - part: "Cuerpo de la Tesis"
      chapters:
        - 02-capitulo-1-marco-teorico.qmd
        - 03-capitulo-2-fundamentos.qmd
        - 04-capitulo-3-diseno-experimental.qmd
        - 05-capitulo-4-resultados.qmd
        - 06-capitulo-5-conclusiones.qmd
    - 07-referencias.qmd
    - 08-apendices.qmd

format:
  docx:
    reference-doc: assets/Plantilla_Tesis_Doctorado.docx
    toc: true
    number-sections: true

bibliography: references.bib
citeproc: true
